backend:
  name: github
  repo: Masked-Kunsiquat/cstate2
  branch: master
  base_url: https://sveltia-cms-auth.blaine005.workers.dev/
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "Upload “{{path}}”"
    deleteMedia: "Delete “{{path}}”"

media_folder: /static/img
public_folder: /img

collections:
  - name: "status"
    label: "System Status"
    folder: "content/status"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Status", name: "status", widget: "select", options: ["Operational", "Degraded Performance", "Partial Outage", "Major Outage"]}
      - {label: "Affected Services", name: "affected_services", widget: "list"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Resolution", name: "resolution", widget: "markdown"}

  - name: "maintenance"
    label: "Scheduled Maintenance"
    folder: "content/maintenance"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Maintenance Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Start Date", name: "start_date", widget: "datetime"}
      - {label: "End Date", name: "end_date", widget: "datetime"}
      - {label: "Affected Services", name: "affected_services", widget: "list"}
      - {label: "Details", name: "details", widget: "markdown"}
      - {label: "Informational", name: "informational", widget: "boolean", default: false}

  - name: "issues"
    label: "Incident Reports"
    folder: "content/issues"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Resolved", name: "resolved", widget: "boolean", default: false}
      - {label: "Resolved When", name: "resolvedWhen", widget: "datetime"}
      - {label: "Severity", name: "severity", widget: "select", options: ["down", "disrupted", "notice"]}
      - {label: "Affected Systems", name: "affected", widget: "list"}
      - {label: "Section", name: "section", widget: "hidden", default: "issue"}
      - {label: "Description", name: "description", widget: "markdown"}
