backend:
  name: github
  repo: Masked-Kunsiquat/cstate2
  branch: master
  base_url: https://sveltia-cms-auth.blaine005.workers.dev/
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "Upload “{{path}}”"
    deleteMedia: "Delete “{{path}}”"

media_folder: /static/img
public_folder: /img

collections:
  - name: "status"
    label: "Status"
    folder: "content/issues"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Resolved", name: "resolved", widget: "boolean", default: false}
      - {label: "Resolved Date", name: "resolvedDate", widget: "datetime"}
      - {label: "Severity", name: "severity", widget: "select", options: ["down", "disrupted", "notice"]}
      - {label: "Affected Systems", name: "affected", widget: "list"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "More Info", name: "body", widget: "markdown"}
